# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('release_date', models.DateTimeField(verbose_name='Release Date')),
                ('runtime', models.IntegerField()),
            ],
        ),
    ]
