# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(verbose_name='Release Date'),
        ),
    ]
