# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 05:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0002_auto_20161108_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='datetime_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='format',
            field=models.CharField(choices=[('BRD', 'BRD'), ('DVD', 'DVD'), ('VHS', 'VHS')], default='BRD', max_length=3),
        ),
        migrations.AlterField(
            model_name='movie',
            name='runtime',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=250, unique_for_year='release_date'),
        ),
    ]
